version: '2'
services:
  rawgithack:
    build:
      context: ../
      dockerfile: .docker/Dockerfile
    restart: always
    volumes:
      - cache:/var/cache/nginx/rawgithack:rw
      - ../config.lua:/etc/nginx/rawgithack/config.lua
      - ../rawgithack.conf:/etc/nginx/rawgithack/rawgithack.conf
    ports:
      - "80:80"

volumes:
  cache:
